AddCSLuaFile("easychat/client/font_extensions.lua")
AddCSLuaFile("easychat/migrations.lua")
AddCSLuaFile("easychat/easychat.lua")
AddCSLuaFile("easychat/autoloader.lua")

AddCSLuaFile("easychat/client/expressions.lua")
AddCSLuaFile("easychat/client/chatbox_panel.lua")
AddCSLuaFile("easychat/client/chat_tab.lua")
AddCSLuaFile("easychat/client/settings_tab.lua")
AddCSLuaFile("easychat/client/chathud.lua")
AddCSLuaFile("easychat/client/markup.lua")
AddCSLuaFile("easychat/client/macro_processor.lua")
AddCSLuaFile("easychat/client/chathud_font_editor_panel.lua")

include("easychat/client/font_extensions.lua")
include("easychat/migrations.lua")
include("easychat/easychat.lua")